package com.example.IngreWiz.model;

public enum Category {
    ITALIAN, CHINESE, INDIAN, MEXICAN, AMERICAN, FRENCH, JAPANESE, KOREAN, THAI, VIETNAMESE, MALAYSIAN, FILIPINO, SPANISH, ARABIAN, TURKISH, MOROCCAN, ETHIOPIAN, NIGERIAN, BRAZILIAN, CANADIAN

}
